# Generated by Django 4.2.24 on 2025-10-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantimage",
            name="image",
            field=models.ImageField(upload_to="media/flowers/"),
        ),
    ]
