# Generated by Django 4.2.24 on 2025-10-30 05:31

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowerimage",
            name="image",
            field=models.ImageField(
                upload_to="media/flowers/",
                validators=[catalog.validators.validate_file_size],
            ),
        ),
    ]
