# Generated by Django 4.2.24 on 2025-10-30 16:35

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_flowerimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowerimage",
            name="image",
            field=models.ImageField(
                default="media/florivo/image_icon_fsvtyo",
                upload_to="florivo/catalog_images/",
                validators=[catalog.validators.validate_file_size],
            ),
        ),
    ]
