# Generated by Django 4.2.24 on 2025-10-28 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="flower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.flower"
            ),
        ),
    ]
